# Header
menu:
  Home: 
    title: Home
    url: /
    icon: fa fa-home fa-fw
  Archives: 
    title: Archives
    url: /archives/
    icon: fa fa-archive fa-fw
  Tags: 
    title: Tags
    url: /tags/
    icon: fa fa-tags fa-fw
  About: 
    title: About
    url: /about/
    icon: fa fa-user fa-fw
iconmenu:
  Github:
    url: https://github.com/DiruSec
    icon: fa fa-github fa-fw
  Twitter:
    url: https://twitter.com/DiruSec
    icon: fa fa-twitter fa-fw
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: